modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
logoFile="../assets/${mod_id}/icon.png"
credits="${credits}"
authors = "${mod_author}"
description = '''${description}'''

[[stator]]
main = [ "com.example.examplemod.ExampleMod" ]
client = [ "com.example.examplemod.client.ExampleModClient" ]

[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.client.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type="required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type="required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "dynamo"
type="required"
versionRange = "${dynamo_version_range}"
ordering = "NONE"
side = "BOTH"
